In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Q1

In [29]:
def decomp1d(n, num_blocks, sub_mat_index):
    """_summary_

    Args:
        n (int): matrix lenght
        num_blocks (int): number of blocks to split into
        sub_mat_index (int): index of sub matrix row

    Returns:
        _type_: _description_
    """
    remainder = n % num_blocks
    base = n // num_blocks

    if (sub_mat_index < remainder):
        s =  sub_mat_index * (base+1)
        e = (sub_mat_index * (base+1)) + base+1
        return s, e  # start, end
    else:
        s = (remainder * (base+1) * remainder) + ((max(sub_mat_index-remainder, 0)) * base)
        e = (remainder * (base+1) * remainder) + ((max(sub_mat_index-remainder, 0)) * base) + base
        return s, e 
   
def decomp_matrix(A, num_blocks):
    a = [[0]*num_blocks for i in range(num_blocks)]
    m, n = A.shape
    
    for i in range(num_blocks):
        for j in range(num_blocks):
            s1, e1 = decomp1d(m, num_blocks, i)
            s2, e2 = decomp1d(n, num_blocks, j)
            a[i][j] = A[s1:e1, s2: e2]
    
    return a            

def TSQR(A, num_rows):
    A = decomp_matrix(A, num_rows)
    
    
#    return Q, R

    

In [30]:
A = np.eye(10)
num = 3  
for i in range(num):
    for j in range(num):
        print(i, j)
        print(decomp_matrix(A, num)[i][j])

0 0
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
0 1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
0 2
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
1 0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1 2
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2 0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2 1
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2 2
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
